// Generated by CoffeeScript 1.10.0
var bodies, img, onFrame, size, text;

size = new Size(800, 400);

text = new PointText({
  point: new Point(0, size.height - 50),
  fillColor: "red",
  fontSize: 40
});

bodies = [];

img = document.getElementById("box");

onFrame = function(e) {
  var fps, i, len, rect, results;
  fps = Math.floor(e.count / e.time);
  text.content = "FPS: " + fps + "   COUNT OBJECTS: " + bodies.length;
  results = [];
  for (i = 0, len = bodies.length; i < len; i++) {
    rect = bodies[i];
    rect.size = new Size(50, 50);
    results.push(rect.rotate(600 * e.delta));
  }
  return results;
};

setInterval(function() {
  var randPos;
  randPos = Point.random() * new Point(size.width, size.height - 100);
  return bodies.push(new Raster(img, randPos));
}, 10);
