// Generated by CoffeeScript 1.10.0
(function() {
  window.onload = function() {
    var bodies, box, rects, renderer, stage, textFPS, ticker;
    renderer = PIXI.autoDetectRenderer(1000, 800, {
      backgroundColor: 0x698AE8
    });
    document.body.appendChild(renderer.view);
    textFPS = new PIXI.Text("", {
      font: "bold italic 36px Arial",
      fill: "#F7EDCA"
    });
    textFPS.x = 0;
    textFPS.y = 0;
    box = PIXI.Texture.fromImage('box.png');
    bodies = [];
    setInterval(function() {
      var rect, x, y;
      x = Math.floor(Math.random() * 1000);
      y = Math.floor(Math.random() * 800);
      rect = new PIXI.Sprite(box);
      rect.position.set(x, y);
      rect.height = 50;
      rect.width = 50;
      rect.anchor.set(0.5, 0.5);
      rects.addChild(rect);
      return bodies.push(rect);
    }, 10);
    stage = new PIXI.Container;
    rects = new PIXI.Container;
    stage.addChild(rects);
    stage.addChild(textFPS);
    ticker = new PIXI.ticker.Ticker;
    ticker.add(function() {
      var i, len, rect;
      textFPS.text = "FPS: " + (Math.floor(ticker.FPS)) + "   COUNT OBJECTS: " + bodies.length;
      for (i = 0, len = bodies.length; i < len; i++) {
        rect = bodies[i];
        rect.rotation += 0.1;
      }
      return renderer.render(stage);
    });
    return ticker.start();
  };

}).call(this);
